"""Shared attribution model interface and result types."""

from __future__ import annotations

from abc import ABC, abstractmethod
from collections import defaultdict
from collections.abc import Iterable
from dataclasses import dataclass

import pandas as pd

from ..journeys import Journey, JourneyCollection

ATTRIBUTION_COLUMNS = ["channel", "attribution_credit", "share", "conversions"]


class AttributionError(ValueError):
    """Raised when attribution cannot be calculated."""


@dataclass(frozen=True, slots=True)
class AttributionResult:
    """Tabular channel attribution generated by a named model."""

    model: str
    data: pd.DataFrame

    def __post_init__(self) -> None:
        missing = set(ATTRIBUTION_COLUMNS) - set(self.data.columns)
        if missing:
            raise AttributionError(f"Attribution output is missing columns: {sorted(missing)}")


class AttributionModel(ABC):
    """Common stateful interface implemented by all attribution models.

    ``fit(journeys)`` stores the journey population and ``attribute()`` computes
    attribution.  For convenience and backwards compatibility,
    ``attribute(journeys)`` fits and computes in one call.
    """

    name: str

    def __init__(self) -> None:
        self.journeys_: tuple[Journey, ...] | None = None

    def fit(self, journeys: JourneyCollection | Iterable[Journey]) -> AttributionModel:
        """Fit the model to a materialized journey population."""

        records = journeys.journeys if isinstance(journeys, JourneyCollection) else tuple(journeys)
        self.journeys_ = tuple(records)
        return self

    def attribute(
        self, journeys: JourneyCollection | Iterable[Journey] | None = None
    ) -> AttributionResult:
        """Allocate conversion value and counts across channels."""

        if journeys is not None:
            self.fit(journeys)
        if self.journeys_ is None:
            raise AttributionError("Call fit(journeys) before attribute().")
        return self._attribute_fitted()

    def _attribute_fitted(self) -> AttributionResult:
        value_credit: defaultdict[str, float] = defaultdict(float)
        conversion_credit: defaultdict[str, float] = defaultdict(float)
        for journey in self.journeys_ or ():
            if not journey.converted:
                continue
            weights = self._weights(journey)
            if not weights:
                raise AttributionError("A converted journey produced no channel weights.")
            total = sum(weight for _, weight in weights)
            if total <= 0:
                raise AttributionError("Attribution weights must sum to a positive value.")
            for channel, weight in weights:
                normalized = weight / total
                value_credit[channel] += normalized * journey.conversion_value
                conversion_credit[channel] += normalized
        return make_attribution_result(self.name, value_credit, conversion_credit)

    @abstractmethod
    def _weights(self, journey: Journey) -> list[tuple[str, float]]:
        """Return potentially repeated channel-weight pairs for one journey."""


def make_attribution_result(
    model: str,
    value_credit: dict[str, float],
    conversion_credit: dict[str, float],
) -> AttributionResult:
    """Build a consistently ordered public result table."""

    total_value = sum(value_credit.values())
    rows = [
        {
            "channel": channel,
            "attribution_credit": credit,
            "share": credit / total_value if total_value else 0.0,
            "conversions": conversion_credit.get(channel, 0.0),
        }
        for channel, credit in value_credit.items()
    ]
    data = pd.DataFrame(rows, columns=ATTRIBUTION_COLUMNS)
    if not data.empty:
        data = data.sort_values(
            ["attribution_credit", "channel"], ascending=[False, True], ignore_index=True
        )
    return AttributionResult(model=model, data=data)
