"""Public API for mta-audit."""

from .attribution import (
    ATTRIBUTION_COLUMNS,
    AttributionError,
    AttributionModel,
    AttributionResult,
    FirstTouchAttribution,
    LastTouchAttribution,
    LinearAttribution,
    MarkovAttribution,
    MarkovChainAttribution,
)
from .audit import MTAAudit
from .audits import (
    ChannelConcentrationMetrics,
    ConcentrationStats,
    ContaminationMetrics,
    ContaminationThresholds,
    ConversionWindowMetrics,
    ConversionWindowThresholds,
    ExposureComparisonMetrics,
    ExposureGroupStats,
    ExposureThresholds,
    LeakageSimulationMetrics,
    ModelDisagreementMetrics,
    PathSparsityMetrics,
    SimulationScenario,
    TemporalStabilityMetrics,
    TemporalStabilityThresholds,
    audit_channel_concentration,
    audit_conversion_window,
    audit_delayed_converter_contamination,
    audit_event_loss,
    audit_exposure_comparison,
    audit_identity_loss,
    audit_model_disagreement,
    audit_model_stability,
    audit_path_sparsity,
    audit_temporal_stability,
    audit_touchpoint_loss,
    calculate_channel_concentration,
    calculate_exposure_comparison,
    calculate_model_disagreement,
    calculate_path_sparsity,
    resolve_attribution_model,
)
from .bootstrap import BootstrapConfig, BootstrapResult, bootstrap_attribution
from .checks import run_data_quality_checks, run_duplicate_checks
from .datasets import (
    CriteoAttributionAdapter,
    DatasetNotAvailableError,
    SyntheticStressScenario,
    load_criteo_attribution,
    load_ignazio_attribution,
    load_synthetic_attribution,
    load_triangulation_mta,
    make_stress_scenario,
    simulate_criteo_label_events,
    simulate_jd_mta_events,
    simulate_synthesizer_events,
    transform_ignazio_touchpoints,
    transform_synthesizer_touchpoints,
    transform_synthetic_attribution,
    transform_triangulation_mta,
)
from .journeys import (
    Journey,
    JourneyBuilder,
    JourneyCollection,
    JourneyError,
    JourneySummary,
    Touchpoint,
    build_journeys,
)
from .results import (
    AuditFinding,
    AuditReport,
    AuditResult,
    AuditScore,
    EvidenceStatus,
    Severity,
)
from .robustness import DecisionRobustnessResult, SensitivityResult
from .sampling import sample_for_audit
from .schema import ColumnMapping, SchemaError, ValidationSummary, validate_events
from .scoring import (
    COMPONENT_CHECKS,
    ScoreThresholds,
    ScoringWeights,
    calculate_reliability_score,
    score_label,
)
from .simulation import (
    CorruptedFrame,
    CorruptionMetadata,
    corrupt,
    deduplicate,
    detect_duplicates,
)

__all__ = [
    "ATTRIBUTION_COLUMNS",
    "COMPONENT_CHECKS",
    "AttributionError",
    "AttributionModel",
    "AttributionResult",
    "AuditFinding",
    "AuditReport",
    "AuditResult",
    "AuditScore",
    "BootstrapConfig",
    "BootstrapResult",
    "ChannelConcentrationMetrics",
    "ColumnMapping",
    "ConcentrationStats",
    "ContaminationMetrics",
    "ContaminationThresholds",
    "ConversionWindowMetrics",
    "ConversionWindowThresholds",
    "CorruptedFrame",
    "CorruptionMetadata",
    "CriteoAttributionAdapter",
    "DatasetNotAvailableError",
    "DecisionRobustnessResult",
    "EvidenceStatus",
    "ExposureComparisonMetrics",
    "ExposureGroupStats",
    "ExposureThresholds",
    "FirstTouchAttribution",
    "Journey",
    "JourneyBuilder",
    "JourneyCollection",
    "JourneyError",
    "JourneySummary",
    "LastTouchAttribution",
    "LeakageSimulationMetrics",
    "LinearAttribution",
    "MTAAudit",
    "MarkovAttribution",
    "MarkovChainAttribution",
    "ModelDisagreementMetrics",
    "PathSparsityMetrics",
    "SchemaError",
    "ScoreThresholds",
    "ScoringWeights",
    "SensitivityResult",
    "Severity",
    "SimulationScenario",
    "SyntheticStressScenario",
    "TemporalStabilityMetrics",
    "TemporalStabilityThresholds",
    "Touchpoint",
    "ValidationSummary",
    "audit_channel_concentration",
    "audit_conversion_window",
    "audit_delayed_converter_contamination",
    "audit_event_loss",
    "audit_exposure_comparison",
    "audit_identity_loss",
    "audit_model_disagreement",
    "audit_model_stability",
    "audit_path_sparsity",
    "audit_temporal_stability",
    "audit_touchpoint_loss",
    "bootstrap_attribution",
    "build_journeys",
    "calculate_channel_concentration",
    "calculate_exposure_comparison",
    "calculate_model_disagreement",
    "calculate_path_sparsity",
    "calculate_reliability_score",
    "corrupt",
    "deduplicate",
    "detect_duplicates",
    "load_criteo_attribution",
    "load_ignazio_attribution",
    "load_synthetic_attribution",
    "load_triangulation_mta",
    "make_stress_scenario",
    "resolve_attribution_model",
    "run_data_quality_checks",
    "run_duplicate_checks",
    "sample_for_audit",
    "score_label",
    "simulate_criteo_label_events",
    "simulate_jd_mta_events",
    "simulate_synthesizer_events",
    "transform_ignazio_touchpoints",
    "transform_synthesizer_touchpoints",
    "transform_synthetic_attribution",
    "transform_triangulation_mta",
    "validate_events",
]

__version__ = "0.1.2"
